### ISSUE TITLE
[Project Add]: Legions of Fire

### ISSUE THREAD

**Issue by Civic06** [North101/mpc_projects#56]
**Cards:**
https://drive.google.com/drive/folders/1FJbEcRNwFuxguqfdHJBt48aYVEtIvyh0?usp=drive_link

**Description:**
You have spent several fruitless weeks in the city of Rome, hoping to solve a series of disturbing ritual murders with victims who have been burned alive. Despite your considerable experience, you’ve hit a dead-end, that is, until a letter invites you to Vatican City with a worrying tale of destruction, rapture, and a cult intent on setting the world ablaze…

**Link:**
http://arkhamcentral.com/index.php/legions-of-fire/

**Image:**
![Cover Image](https://github.com/North101/mpc_projects/assets/163741734/420db894-814c-43e7-aa6a-091fea94d4f7)

**Comment by brightbold** [comment]
@Civic06 So so sorry this took me so long!
